version: "3.8"

# Development environment override
services:
  php:
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./back:/srv/app:rw,cached
      - ./back/docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
    environment:
      APP_ENV: dev

  caddy_back:
    volumes:
      - ./back/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./back/public:/srv/app/public:ro

  database:
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  
  vite:
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./front:/srv/app:rw,cached
  
  caddy_front:
    volumes:
      - ./front/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025"
      - "1080"

volumes:
  db-data:
